FromDoppler/mailerq-dotnet-sdk

- MailerQ/Core/IQueueManager.cs
- MailerQ/Core/QueueManager.cs
- appveyor.yml
This allow to finish an individual subscription without need dispose the bus.
> Change Subscribe* methods to return IDisposable instance

- MailerQ/Core/QueueManager.cs
- appveyor.yml
This allow EasyNetQ catch any exception on the handle, and generate the special ErrorMessage to push to the default error message queue.
> Waits for the handle completes.

- MailerQ/Core/QueueManager.cs
- MailerQ/MailerQ.csproj
This allow inject the MailerQConfiguration instance using IOptions pattern from the configuration service like this
`services.Configure<MailerQConfiguration>(configuration.GetSection(nameof(MailerQConfiguration)));`
> [DM-93] Add new constructor that accept configure using IOptions pattern

- .config/dotnet-tools.json
- .editorconfig
- MailerQ.Test/MessageStorageTest.cs
- MailerQ.code-workspace
- MailerQ.sln
- MailerQ/Conventions/Canonicalization.cs
- MailerQ/Core/QueueManager.cs
- MailerQ/Json/SingleOrArrayConverter.cs
- MailerQ/MessageStore/MessageStorage.cs
- MailerQ/MessageStore/MongoDBMessageStorage.cs
- MailerQ/Mime/Mime.cs
- README.md
- appveyor.yml
Add `editorconfig` for .NET coding convention settings
See https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference
> Add editorconfig

- .github/workflows/dotnetcore.yml
- MailerQ.sln
- README.md
This is for setup Github actions to complement (or in the future replace) AppVeyor
> chore: add dotnetcore github actions workflow

- MailerQ/MailerQ.csproj
- MailerQ/MessageStore/IMessageStorage.cs
- MailerQ/MessageStore/MessageStorage.cs
- MailerQ/MessageStore/MongoDBMessageStorage.cs
Also move to net standard 2.1 to use C# 8 features
> feat: allow set message stored expiration on insert

- MailerQ/DeliveryState.cs
Related to: [DM-357](https://makingsense.atlassian.net/browse/DM-357)
See *Delivery states* section in [*Result message queues*](https://www.mailerq.com/documentation/5.8/json-results)  documentation
> [DM-357] Add new delivery states of v5.8

- .github/workflows/dotnetcore.yml
- .github/workflows/publish.yml
- MailerQ.sln
- MailerQ/MailerQ.csproj
Separate build and test from publish nuget
Generate documentation file to include into the nuget package
> Improve GitHub actions

- .github/workflows/gitversion.yml
This PR is for add a _Github Action_ to determine the *semantic version* using _GitVersion tool_.
See: https://github.com/GitTools/actions
> chore(ci): determine semver with github action

- .github/workflows/publish.yml
This PR is to publish _nuget_ on _GitHub Packages_ when a new version tag is created
> Publish nuget on GitHub package

- MailerQ/OutgoingMessage.cs
> refactor: remove obsolete DeliveryGuid

- MailerQ/MailerQ.csproj
The last version use Rabbit.Client 6.1 that has some problems in some scenarios
> chore(deps)): downgrade EasyNetQ from 5.2.0 to 5.1.2

- MailerQ/MailerQ.csproj
Reverts MakingSense/mailerq-dotnet-sdk#84
> Revert "chore(deps): bump EasyNetQ from 5.1.2 to 5.3.0"

- MailerQ/Core/QueueManager.cs
> fix: use connectionConfiguration instead of connection string

- MailerQ/Conventions/StorageEngines.cs
- MailerQ/EmailAddressParts.cs
- MailerQ/RestApi/ExternalIP.cs
- MailerQ/ResultMessage.cs
- MailerQ/SentInfo.cs
See https://github.com/CopernicaMarketingSoftware/Documentation/commits/master/Mailerq/5.9
> Add support for v5.9

- MailerQ.Test/JsonDeserializeTest.cs
- MailerQ.Test/MailerQ.Test.csproj
- MailerQ.Test/json-examples/incomming-message-from-cli.json
- MailerQ.Test/json-examples/incomming-message-from-rest-api.json
- MailerQ.Test/json-examples/incomming-message-from-spool.json
- MailerQ.Test/json-examples/incomming-message-from-tcp.json
- MailerQ.Test/json-examples/incomming-message-with-check-results.json
- MailerQ.Test/json-examples/incomming-message.json
- MailerQ.Test/json-examples/outgoing-message-with-many-options.json
- MailerQ.Test/json-examples/outgoing-message-with-responsive-email-mime.json
- MailerQ.Test/json-examples/outgoing-message.json
- MailerQ.Test/json-examples/readme.md
- MailerQ.Test/json-examples/result-message-with-added-properties.json
- MailerQ.Test/json-examples/result-message-with-secure-connections.json
- MailerQ.Test/json-examples/result-message.json
Related to: [DM-632](https://makingsense.atlassian.net/browse/DM-632)
> Add json deserialize tests

- MailerQ/Core/IQueueManager.cs
- MailerQ/Core/IQueuePublisher.cs
- MailerQ/Core/IQueueSubscriber.cs
- MailerQ/Core/QueueManager.cs
Related to: [DM-638](https://makingsense.atlassian.net/browse/DM-638)
This PR is for
- split the interfaces for publish and subscribe
- add methods to publish in batch
> Refactor queue manager

- MailerQ/Core/IQueuePublisher.cs
- MailerQ/Core/QueueManager.cs
- MailerQ/Core/RabbitMQClientPublisher.cs
This implementation use the _RabbitMQ.Client_, the same used by _EasyNetQ_.
The client allow publish messages in batch writing in the same socket connection, this improve the performance a lot with many little messages
Related to: [DM-642](https://makingsense.atlassian.net/browse/DM-642)
> [DM-642] feat: new IQueuePublisher implemented with RabbitMQ.Client

- MailerQ/Core/QueueManager.cs
- MailerQ/Core/RabbitMQClientPublisher.cs
- MailerQ/MailerQ.csproj
This PR is for update _EasyNetQ_ and fix the breaking changes that affect to _mailerq-dotnet-sdk_
Related to: [DM-730](https://makingsense.atlassian.net/browse/DM-730)
> [DM-730] Bump EasyNetQ from v5 to v6

- MailerQ/Core/MailerQConfiguration.cs
See https://www.mailerq.com/documentation/5.13/rest-api-v1 for more information
> feat: add settings to allow use _MailerQ Rest Api_

- .github/workflows/codeql-analysis.yml
Configure _Code QL_ analyzer tool as _Github Action_
More information [here](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning)
> chore(ci): configure codeql analysis

- MailerQ/Dkim.cs
- MailerQ/Json/DateTimeConverter.cs
- MailerQ/Json/MailerQDateTimeConverter.cs
- MailerQ/OutgoingMessage.cs
The default format in serialization is `2022-05-15T18:36:04.2297419Z`
_MailerQ_ use this format `2022-05-12 18:36:04`
> [DD-930] format datetime on json serialization

- .github/workflows/dotnet.yml
Replace GitHub repository owner with GitHub environment variable
> chore: improve .NET github action

- MailerQ/MailerQ.csproj
This repository was moved from _MakingSense_ to _FromDoppler_
> chore(cd): update authors and company values
